config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'pages/home'

  get 'pages/about'

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end 

  resources :users
  resources :playlists
  resources :songs
  resources :genres
  resources :songs do
	resources :comments
  end

  root :to => 'pages#home'

end

app/models/song.rb
class Song < ActiveRecord::Base

	belongs_to :genre
	
	validates :title, presence: true
	validates :rating, presence: true
	
	has_many :comments, dependent: :destroy
	
	def average_stars
		comments.average(:stars)
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :album, :genre_id, :date_released)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :date_released %><br>
    <%= f.date_select :date_released %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>
<style>
table {
    border-collapse: collapse;
}

table, th, td {
    border: 1px solid black;
}
</style>
<h1>Listing Songs</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Date released</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
		<td><%= image_tag(song.album,:size=>"80x50")%></td
        <td><%= song.genre_id %></td>
        <td><%= song.date_released %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @song.genre_id %>
</p>

<p>
  <strong>Date released:</strong>
  <%= @song.date_released %>
</p>

<h2>Rating and comment:</h2>
	<%= form_for([@song, Comment.new]) do |f| %>
	
	<h3><%= f.label :stars %> 
	  <% stars = [1, 2 ,3 ,4 ,5] %>
	  <% stars.each do |star| %>
		<%= f.radio_button :stars,star %> <%= star %>
	  <% end %>
	 
	</h3></br>
	<%= f.text_area :content, :rows => 4, :cols => 40 %>
	<div class ="actions">
		<%= f.submit "Post Comment" %>
	</div>
	<% end %>
	
	<% if @song.comments.empty? %>
		<h3>You are the first commenter</h3>
	<% else %>
		<h2>Other users comments:</h2>
		<% @song.comments.reverse.each do |comment| %>
			<p><%= comment.content %>
			Posted <%= time_ago_in_words(comment.created_at) %> ago by
			<%= comment.user.username %></p>
		<% end %>
		<h3> Rating </h3>
		<p>
			<% number_with_precision( @movie.average_stars, precision: 0) %>
			</p>
		<% end %>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>